### ISSUE TITLE
Liga Oeste en vez de liga Este, ¿cómo conseguir los datos?

### ISSUE THREAD

**Issue by Aimonius** [IvoVillanueva/LEB_PLATA#1]
Saludos Ivo, felicidades por todos estos trabajo. En el caso de la LEB_PLATA, al reproducir tu script , siempre salen por defecto los datos de la Liga Regular "ESTE". ¿Cómo habría que hacer para escrapear los de la Liga Regular OESTE? Al estar en una pestaña distinta no consigo nada...

Gracias.

**Comment by IvoVillanueva** [comment]
Hola Jesús muchas gracias
Esta noche te mando la solución
Un saludo

Iván Villanueva

El 13 nov 2023, a las 11:49, Jesus ***@***.***> escribió:

﻿

Saludos Ivo, felicidades por todos estos trabajo. En el caso de la LEB_PLATA, al reproducir tu script , siempre salen por defecto los datos de la Liga Regular "ESTE". ¿Cómo habría que hacer para escrapear los de la Liga Regular OESTE? Al estar en una pestaña distinta no consigo nada...

Gracias.

**Comment by IvoVillanueva** [comment]
Aquí tienes la solución:
No se si te has fijado que al cambiar la pestaña de "LIga Regular 'ESTE'" que sale por defecto a 'OESTE', el link cambia de https://www.lebplata.es/estadisticas.aspx a https://www.lebplata.es/Inicio.aspx?tabid=8 bueno pues usando este ultimo link tenemos que usar el siguiente código
```
url -> https://www.lebplata.es/Inicio.aspx?tabid=8
pgsession <- session(url) 
pgform <- html_form(pgsession)[[1]]
leb <- html_form_set(pgform,
                     "_ctl0:temporadasDropDownList" = 2023,
                    "_ctl0:fasesGruposDropDownList" = 83085
)
```
ok, tenemos que abrir una sesión con el link y luego con html_form averiguar los desplegables, 
<img width="368" alt="Captura de pantalla 2023-11-14 a las 0 04 14" src="https://github.com/IvoVillanueva/LEB_PLATA/assets/56939175/2a211a18-ede7-4350-af05-8752f1071567">
ahí nos damos cuenta que podemos elegir el año y la fase regular que queramos 83084 para la este y 83085 para la oeste,  esto se averigua con botón derecho inspeccionar y en el código html lo veras 
[
<img width="695" alt="Captura de pantalla 2023-11-14 a las 0 18 18" src="https://github.com/IvoVillanueva/LEB_PLATA/assets/56939175/b7aab647-8439-46f7-9af4-bec8b678f479">
](url)
una vez que tenemos seleccionadas las pestañas con la declaración "leb" tecleamos lo siguiente 
`df -> session_submit(pgsession, form = leb, POST = url)`

y ahora ya podemos buscar los datos
```
totales  <- df %>%
    read_html() %>%
    html_element("table:nth-of-type(2)") %>%
    html_table() %>%
    row_to_names(row_number = 1) %>%
    clean_names() %>%
    separate(t2, c("t2_c", "t2_i"), "/") %>% #seperamos los tiros en convertidos e intentados
    separate(t3, c("t3_c", "t3_i"), "/") %>%
    separate(tc, c("tot_c", "tot_i"), "/") %>%
    separate(tl, c("tl_c", "tl_i"), "/") %>%
    mutate(across(c(par:va), parse_number))
```
Aquí nos da ya la oeste, para la este o pones 83084 o el primer link. Puedes generar una función que te descargue las dos en una sola tabla.
Cualquier cosa me dices
Un saludo.

**Comment by Aimonius** [comment]
Perfecto Ivo, me ha quedado todo el proceso muy claro. Muchísimas gracias. Saludos.

**Comment by IvoVillanueva** [comment]
Cierro este Issue gracias a ti.
